### ISSUE TITLE
Multi-Peer Support

### ISSUE THREAD

**Issue by Stxyl** [simonbengtsson/simple_peer_flutter#2]
Hey There!

I am brand new to WebRTC and trying to wrap my head around all this for a school project,
I was reading the Simple Peer (js) GitHub and there is support for Multiple Peer transfer (so more than 2 peers for example 3 and more).
I was wondering if this flutter package has support for this since I am building a project that requires to send files (Photos and Videos of various sizes) from one device to 2 other (or more) devices.

If it is possible, I would love to contact anyone 1 on 1 about this package to well further understand how WebRTC and this package works as a whole, learning curve for me

Thanks :)

**Comment by simonbengtsson** [comment]
Hi! Not supported so you would need to open many connections for that.

Curious though, whats the use case?

**Comment by Stxyl** [comment]
If you have discord you can contact me here @Stxyl 
I am happy to talk about the use case from there
